openapi: 3.0.1
info:
  title: Example API
  description: This is an example API using OpenAPI
  version: 1.0.0
paths:
  /example:
    post:
      parameters:
        - description: Compression format of the request body.
          explode: false
          in: header
          name: Content-Encoding
          required: true
          schema:
            enum:
              - gzip
            type: string
          style: simple
      summary: Example POST endpoint
      operationId: executeRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
components:
  schemas:
    ExampleRequest:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
    ExampleResponse:
      type: object
      properties:
        result:
          type: string
          example: "Success"